# Generated by Django 3.2.2 on 2022-12-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(choices=[('InformationTechnology', 'InformationTechnology'), ('ComputerScience', 'ComputerScience'), ('InformationScience', 'InformationScience'), ('Electronics and Communication', 'Electronics and Communication'), ('Mechanical', 'Mechanical')], default='InformationTechnology', max_length=29),
        ),
    ]
